### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by enobufs** [node-opcua/opcua-commander#8]
When I installed this module globally from npm repository,
```
$ npm install -g opcua-commander
```

I got this error:
```
$ opcua-commander
env: node\r: No such file or directory
```

I found the `bin/opcua-commander` contains `\r` (CR) which causes the above error.

```
$ hexedit opcua-commander
00000000   23 21 2F 75  73 72 2F 62  69 6E 2F 65  6E 76 20 6E  6F 64 65 0D  0A 0D 0A 72  #!/usr/bin/env node....r
00000018   65 71 75 69  72 65 28 22  2E 2E 2F 69  6E 64 65 78  22 29 3B 0D  0A           equire("../index");..
```

I am using macbook pro with node v6.9.0. Installed opcua-commander has version 0.1.7 (gitHead: 456835a540980ec91c5e5493fdb41aa160d41caf)

> This error does not happen if you do git-clone first, probably because it removes CR automatically while cloning...

**Comment by mathieulj** [comment]
I am seeing the same issue under debian linux.

`cat /usr/bin/opcua-commander | hexdump -C` :

    00000000  23 21 2f 75 73 72 2f 62  69 6e 2f 65 6e 76 20 6e  |#!/usr/bin/env n|
    00000010  6f 64 65 0d 0a 0d 0a 72  65 71 75 69 72 65 28 22  |ode....require("|
    00000020  2e 2e 2f 69 6e 64 65 78  22 29 3b 0d 0a           |../index");..|
    0000002d

A quick fix is to remove the windows style line endings via dos2unix:
`sudo dos2unix /usr/lib/node_modules/opcua-commander/bin/opcua-commander`

**Comment by biancode** [comment]
OS X 10.12 the same

**Comment by erossignon** [comment]
Version 0.1.10 has been released and should fix the issue, this version also uses latest node-opcua version.

**Comment by wngr** [comment]
I'm still having the same issue on Fedora 27. Just installed version `0.2.0` from npm.
